edition = "2021"
max_width = 120
hard_tabs = true
match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
binop_separator = "Back"
brace_style = "PreferSameLine"
combine_control_expr = false
