//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "remind")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = true)]
	pub id: u32,
	#[sea_orm(column_type = "Text")]
	pub task_name: String,
	pub author_id: u64,
	pub assignees_id: Option<u32>,
	pub remind_date: ChronoDateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::remind_assignee::Entity",
		from = "Column::AssigneesId",
		to = "super::remind_assignee::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	RemindAssignee,
	#[sea_orm(
		belongs_to = "super::user_data::Entity",
		from = "Column::AuthorId",
		to = "super::user_data::Column::Uid",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	UserData,
}

impl Related<super::remind_assignee::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RemindAssignee.def()
	}
}

impl Related<super::user_data::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserData.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
